version: '3.4'
services:
  start_ethereumjs_client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ethereumjs_client
    volumes:
      - ./execution_data:/execution_data
    ports:
      - '8545:8545'
      - '8551:8551'
    #network_mode: host
    command: >
      --datadir=/execution_data --gethGenesis=./ethereumjs-monorepo/packages/client/kiln/config/genesis.json --rpc --rpcport=8545 --ws --rpcEngine --rpcEnginePort=8551 --saveReceipts --bootnodes=165.232.180.230:30303
